//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoBaseDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int IdJugador { get; set; }
        public string NombreJugador { get; set; }
        public string CorreoJugador { get; set; }
        public string ContraseñaJugador { get; set; }
        public Nullable<int> PuntajeJugador { get; set; }
        public Nullable<int> PuntajeJugadorAlAzar { get; set; }
    }
}
